import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Script from 'next/script'
import { Navbar } from './_ui/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Guess the Song',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar /> */}
        <main className="flex mx-auto min-h-screen flex-col items-center p-4 max-w-screen-md">
          {children}
        </main>
      </body>
      <Script src="https://open.spotify.com/embed/iframe-api/v1" />
    </html>
  )
}
